### ISSUE TITLE
Docker install script relocated

### ISSUE THREAD

**Issue by XNinety9** [geerlingguy/ansible-role-docker_arm#36]
Hi.

Docker install script has been relocated from

```
https://get.docker.com/tmp/get-docker.sh
```

to

```
https://get.docker.com/
```

Your script is broken without this modification.

**Comment by rizlas** [comment]
Hi,
which error are you getting?

Currently download task is correct.

https://github.com/geerlingguy/ansible-role-docker_arm/blob/master/tasks/main.yml#L11

```
- name: Download Docker install convenience script.
  get_url:
    url: https://get.docker.com/
    dest: /tmp/get-docker.sh
    mode: 0775
  when: docker_command_result.rc == 1
```
