### ISSUE TITLE
The gpg keys on the get-docker.sh script dont work.

### ISSUE THREAD

**Issue by thomasbinny** [geerlingguy/ansible-role-docker_arm#39]
**Error:** fatal: [xxxxxxx]: FAILED! => {"changed": false, "msg": "E:Conflicting values set for option Signed-By regarding source https://download.docker.com/linux/ubuntu/ jammy: /etc/apt/keyrings/docker.gpg != , E:The list of sources could not be read."}

**Fix:**  Had to remove "signed-by=/etc/apt/keyrings/docker.gpg" from the apt_repo variable to make it work.
Downloaded your role, made the updates to the script get-docker.sh [script url](https://get.docker.com ) and used the below changes to work with your ansible role.
`apt_repo="deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] $DOWNLOAD_URL/linux/$lsb_dist $dist_version $CHANNEL"`

```
- name: Copy script to remote host
  copy:
    src: /Users/xxxxx/Library/Mobile Documents/com~apple~CloudDocs/Desktop/day-to-day-files/My-K8s/k8s-init-playbook/scripts/get-docker.sh
    dest: /tmp/get-docker.sh
    mode: '0755'  # Set the appropriate permissions on the script

- name: Execute script on remote host
  command: /tmp/get-docker.sh
```

Would be nice to have this handled while you deprecate this role.
